### ISSUE TITLE
bg.jpg does not appear in web player

### ISSUE THREAD

**Issue by Mercedezs** [tedhinklater/finimalism#1]
It seems that the theme on the Jellyfin web is not using the bg.jpg and is using the themes.css file updated 4 hours ago. I am using server 10.9.2.
![print 2](https://github.com/tedhinklater/finimalism/assets/167591116/98c93b83-e324-43aa-8cda-66a8bed42cb9)
![print 1](https://github.com/tedhinklater/finimalism/assets/167591116/b7ad6ce3-8e37-4198-b252-1e1f6a78d016)

**Comment by tedhinklater** [comment]
When you updated jellyfin, did you replace the theme.css in \web-client\desktop\themes\dark ?

**Comment by Mercedezs** [comment]
Yes, I went through the entire process again, including using the new theme.css file you provided. I ran some more tests, cleared the browser cache just to be sure. The first screenshot with the server screen is back to normal, but the main screen (second screenshot) still lacks the bg.jpg effect. When I click on a movie, it displays correctly; only the main screen is missing the bg.jpg effect. 

I believe it should look like this (this is your screenshot)
![image](https://github.com/tedhinklater/finimalism/assets/167591116/5a2bba84-293d-4d1d-a66c-a74a39d5a9bf)


But mine looks like this:
![print 1](https://github.com/tedhinklater/finimalism/assets/167591116/8cb75223-69f0-45ac-8843-10facc70d575)

**Comment by tedhinklater** [comment]
Thanks for the detailed info, could you possibly give the new theme.css a try? I've used a less specific selector for the bg, hopefully it works.

**Comment by tedhinklater** [comment]
ohhhhh in Home set My Media to My Media (Small). That's the difference. I'll fix it so that both work.

**Comment by tedhinklater** [comment]
ok the new new theme.css works with both My Media and My Media (Small), and it also fixed something else I was thinking about so cheers!

**Comment by Mercedezs** [comment]
I just tested it, setting it as My Media (Small) in the old version, and it worked perfectly. After updating, I cleared the browser cache just to make sure I was using the new version. I had a big problem: it's no longer possible to click on anything, and the screen looks a bit strange. I tested it on other devices that had never logged into Jellyfin before, and the result was the same.

Both with My Media (Small) and My Media, it looks like this:
![print 1](https://github.com/tedhinklater/finimalism/assets/167591116/41f1f6a4-2bb4-46ca-bdca-8d5511cf2565)

**Comment by tedhinklater** [comment]
I've reuploaded the theme.css without that new change.

**Comment by tedhinklater** [comment]
I guess attaching it to the cards themselves wasn't going to work, I've attached it to mainDrawerHandle in the new theme.css, it looks like it works from my end. Thanks again for your help with these bugs.

**Comment by tedhinklater** [comment]
no it looks like if I set a bg for large My Media cards, if you have something in Continue Watching it breaks. I plan to do an overhaul because of the new update and general spaghettiness of everything, hopefully I can fix it soon. For now I can only say the theme works for My Media (Small).

**Comment by Mercedezs** [comment]
Ok, I will use My Media (Small) for now. I'm also trying to solve it, but I haven't succeeded yet. If I manage to get something, I'll make a commit

**Comment by Mercedezs** [comment]
I'm making the final adjustments, but I think I managed to fix it.

**Comment by Mercedezs** [comment]
I made a Pull request, tried my best, CSS isn't my strong suit, but it seems to be 100%. Take a look, I liked your project
