### ISSUE TITLE
10.10.0 broke positioning of buttons

### ISSUE THREAD

**Issue by Mr3DAlien** [tedhinklater/finimalism#11]
![Screenshot 2024-10-31 004259](https://github.com/user-attachments/assets/4b42cb41-9866-4ce0-8a85-66eb32070f2a)

**Comment by tedhinklater** [comment]
I've tried Firefox, Chrome and Jellyfin Media Player but can't reproduce this same bug. the controls are in the normal position for me

add this line to the end of your css to see if it helps

```
.osdTimeText {
  margin-right: auto;
  }
```

if that doesn't work try `64em ` instead of auto

**Comment by Mr3DAlien** [comment]
That in fact did fix it. Maybe try to turn on the new "Ask to Skip" setting for intros and outros. I turned that on and when looking at a video I had that problem.

**Comment by tedhinklater** [comment]
I'll look at that setting, cheers!
