### ISSUE TITLE
Broken Scrolls

### ISSUE THREAD

**Issue by L10Messi10** [tedhinklater/finimalism#14]
It's a great css. But when I tried to navigate to Movies -> Genre It can scroll but seems to be lagging. Also, the backdrop is missing in this page,

In the Movies tab it's fine. In the Suggestion tab it's fine to scroll but the backdrop is missing.

**Comment by tedhinklater** [comment]
Ahh thanks, it turns out I had set the bg to apply behind Section Title and it seemed to load another bg for each section in the genres, making it opaque.

The update fixed it and reduces the amount of bg's loaded to 1, so hopefully it's not laggy now. Thanks again for the info!

**Comment by L10Messi10** [comment]
The issue is still there, have you updated the cdn?

Moreover, I also tried the Jellypane it has the same issue.

**Comment by tedhinklater** [comment]
I sent a purge request to jsdelivr earlier, it rarely updates immediately though. 

> Moreover, I also tried the Jellypane it has the same issue

Yeah the same idiot wrote that, I've applied the same fix now, thanks for the tip
