### ISSUE TITLE
Very Small Logo Area On Mobile

### ISSUE THREAD

**Issue by DrMkdaddy** [tedhinklater/finimalism#18]
![Screenshot_20241118_032317_Jellyfin.jpg](https://github.com/user-attachments/assets/0ed54da4-e7f4-4188-ad94-5164e8710a1c)

![Screenshot_20241118_032537_Jellyfin.jpg](https://github.com/user-attachments/assets/e0bbdfdf-7d54-4d89-9629-49671f217bce)

In both screenshots there seems to be an issue where the areas for the logo/title whatever its called at the top (where the Jellyfin logo is as well as the "Settings" - which is cut off at the top) are cramped, causing things to look a bit ugly.

**Comment by tedhinklater** [comment]
![Screenshot 2024-11-18 131018](https://github.com/user-attachments/assets/7bb09273-8999-43e3-a8e7-a3c02281862c)

Fixed in the update which will come through shortly, add this to your css to get the fix immediately

```
.layout-mobile .flex.align-items-center.flex-grow.headerTop { width: 100vw; padding-left: 0;}
.layout-mobile [dir="ltr"] .pageTitle { margin: 0;}
```

**Comment by DrMkdaddy** [comment]
Thank you very much for all the fixes!
