### ISSUE TITLE
Genre Tags missing

### ISSUE THREAD

**Issue by Oednerich** [tedhinklater/finimalism#19]
Hi,
great jellyfin theme! I like it so much that I think it should be shipped with jellyfin itself.

I have one minor issue, I can't see genre tags (right above studio tag) from movies/shows when opening a movie/show. They're not showing like there are none, but they are there in the metadata. If I remove the finimalism css URL and hit save it reverts to normal with the standard black jellyfin theme and genre tags showing again.
Is this intended behavior? Can I change it somehow?

I'm running the qnap-jellyfin package from pdulvp @10.10.1 on a TS-664
not sure if it matters.

**Comment by tedhinklater** [comment]
I hid the genres, writers and tags, you can add them back by adding these snippets to the custom css box (below the import line)

`.detailsGroupItem.genresGroup, .detailsGroupItem.writersGroup, .itemTags { display: block;}`

**Comment by Oednerich** [comment]
That was fast, thank you so much!
didn't realize it was that easy to customize a skin

**Comment by tedhinklater** [comment]
Very easy! I just make it look difficult :D

If you want to edit more: 

Right-click something and click Inspect, then where it says element { } add whatever you like

![css](https://github.com/user-attachments/assets/52c63cd9-ecfc-4106-b99f-da49150de374)

If you're happy, find the element's location, in this example the div id is _itemDetailPage_ and the class is _itemName infoText parentNameLast_ which, all together, becomes

#itemDetailPage .itemName.infoText.parentNameLast { font-size: 3em; color: rebeccapurple; text-decoration: underline; }

**Comment by Oednerich** [comment]
Thank you again, I'll take back the easy part x)
makes me appreciate your work more though.

since I'm more of a system integration guy than a programmer, I still have my difficulties wrapping my head around all the css stuff.

There's another follow-up bug to the genre display, for some reason it started to do a line break after "Genre" and lists them all in a seperate line instead of the same line.
I'm not able to fix it on my own so I appreciate some help if you can look at it.
![Genres](https://github.com/user-attachments/assets/0dade6f4-64ad-41c0-86a9-8412012f2728)

**Comment by tedhinklater** [comment]
@Oednerich It's flex! not block. Sorry I didn't see this before. This is the right one

```css
.detailsGroupItem.genresGroup, .detailsGroupItem.writersGroup, .itemTags {display: flex;}
```

**Comment by Oednerich** [comment]
> @Oednerich It's flex! not block. Sorry I didn't see this before. This is the right one
> 
> ```css
> .detailsGroupItem.genresGroup, .detailsGroupItem.writersGroup, .itemTags {display: flex;}
> ```

sorry, I should have commented again on this, no worries.
I still had the line manually added, after removing it everything went back to normal.
