### ISSUE TITLE
Playlists & Album displays are a bit scuffed

### ISSUE THREAD

**Issue by RobBlume** [tedhinklater/finimalism#20]
An example of the album issue can be found here
https://793ad.com/ss/v4/firefox_tk3hureHn8.png

Issues - 
Cant play music by left clicking the item, nor does any left click interaction work (visiting artist, or album song is from)

An example of the playlist issue 
https://793ad.com/ss/v4/firefox_3LdnZ2zNwc.png

Issues - 
Left clicking to start playback does work although spacing is scuffed when the playlist contains shows or movies.

Another issue i noticed is once you enter a TV shows season to view its episodes for that season there is no way to easily go back the full season list for that show.

**Comment by tedhinklater** [comment]
Thanks for the info I'll get that fixed today

**Comment by tedhinklater** [comment]
ohhhh it's the episode grid line 

`@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/episode%20grid.css");`

**Comment by tedhinklater** [comment]
> Another issue i noticed is once you enter a TV shows season to view its episodes for that season there is no way to easily go back the full season list for that show.
 
 well that one's fixed (should update shortly) I'll redo the episode grid line & make sure to test it with music/albums/playlists with shows, cheers for the screenshots etc

**Comment by RobBlume** [comment]
Yes i use both the colorized theme + grid lines, Thanks for the fast response!
