### ISSUE TITLE
Chapters/Scenes part only shows a maximum of 8 chapters, scrolling buttons missing (in browser)

### ISSUE THREAD

**Issue by Oednerich** [tedhinklater/finimalism#21]
hey, sorry to bug you again.

I love the new chapter view, where its showing all of them on screen and I can scroll vertically through them instead of the original horizontal view which showed like 4 chapters and you have to use the "<" and ">" buttons to scroll horizontally.

edit: I'm talking about the summary page of a movie/episode, when you click on it.

for some reason it changed and shows a maximum of 8 chapters now (even if there are more), while the > and < buttons to scroll are missing.
They show up though if I half the browser window on my screen (bc it reverts back to the original horizontal view I guess).

can you take a look at it?
Thank you very much in advance!

**Comment by tedhinklater** [comment]
oof sorry, thanks for letting me know, it's [fixed](https://github.com/tedhinklater/finimalism/commit/5d5c9d7b4d73831995d67ddee0c2237e6a1163b9)

you can apply the fix by adding this line to your CSS box in the dashboard, though the update should come through shortly by itself

.emby-scroller-container {max-height: unset!important;}
