### ISSUE TITLE
TVDB and TVmaze Image are Broken

### ISSUE THREAD

**Issue by D-E-N-U** [tedhinklater/finimalism#23]
![grafik](https://github.com/user-attachments/assets/2daabfc3-af55-405b-b825-126a1328be47)

The Images for The TVDB and TVmaze seems to be broken or non existing anymore on the source.

**Comment by tedhinklater** [comment]
Ah thanks I've [done one for TVDb](https://github.com/tedhinklater/finimalism/commit/2f5cecd2e2728ace614d181201596f55f13b6841) it should update soon if it hasn't already, I'll do one for TVmaze now

**Comment by tedhinklater** [comment]
ok that should update soon [fix](https://github.com/tedhinklater/finimalism/commit/5dfe796c1e8cbd4ebb72bac74ffedfbe927a35a0)
