### ISSUE TITLE
Font size so big

### ISSUE THREAD

**Issue by Topbcy** [tedhinklater/finimalism#25]
After applying CSS, I noticed the font size is larger than the default. Is this normal?
I have to scale the webpage down to 67% for it to look much more normal.

**Comment by tedhinklater** [comment]
hey can I ask what resolution / ratio / display scale are you using?

**Comment by Topbcy** [comment]
> hey can I ask what resolution / ratio / display scale are you using?
Hello Sir.
My monitor is 3440x1440 21:9 ，I have to scale the webpage down to 67% for it to look much more normal
If I using 100% for webpage. The font size will so big.
Is there any information I can provide to assist your analysis?
Btw. Thanks your effect. This css very great.

**Comment by tedhinklater** [comment]
I've gone back and simplified things, hopefully the update works better

**Comment by Topbcy** [comment]
> I've gone back and simplified things, hopefully the update works better

Tks, Its look normal.

**Comment by Topbcy** [comment]
> I've gone back and simplified things, hopefully the update works better

Btw,The movie tags disappear, is it normal?
