### ISSUE TITLE
Spacing on mobile start page seems off

### ISSUE THREAD

**Issue by felixschndr** [tedhinklater/finimalism#4]
One minor thing: On the start page on mobile the spacing between the rows looks off:
![Screenshot_20240529_195107_Jellyfin](https://github.com/tedhinklater/finimalism/assets/45742226/00410326-41d9-4b95-a15c-723d98ff09a7)

- Between `Start` (`Startseite`) and `My Media` (`Meine Medien`) is a lot of space (could be less)
- Same between `My Media` (`Meine Medien`) and `Continue watching` (`Weiterschauen`)
- The space between `Continue Watching` and `Next` (`Als Nächstes`) & `Next` (`Als Nächstes`) and `New movies` (`Kürzlich hinzugefügte Filme`) looks good.

--> Maybe you could unify the spacing of the upper two to be the same as the lower two (and maybe even make the space of the (then) four just a little bit smaller, but that's just an idea). What do you think about this?

On desktop it looks good:
![image](https://github.com/tedhinklater/finimalism/assets/45742226/acdc696f-5baf-4c11-b661-e3e58a03d2c2)

**Comment by tedhinklater** [comment]
Hey thanks it should be fixed now

![Untitled-2](https://github.com/tedhinklater/finimalism/assets/66086488/55107da4-786b-4b3f-8867-e6eea5203dd4)

**Comment by felixschndr** [comment]
Thank you very much =)
