### ISSUE TITLE
Background issue on collection page

### ISSUE THREAD

**Issue by Dress4Excess** [tedhinklater/finimalism#6]
Sorry for the inconvenience.

When using a browser (Opera GX and Edge), on every collection page, the background covers the top image and the logo.

On the rest of the pages, it looks fine.

The skin is amazing. Thank you very much for the work done.

![Jellyfin Collection](https://github.com/user-attachments/assets/a97e23fa-17b9-41d4-9047-b22e4b0c3bfe)
![Jellyfin Movie](https://github.com/user-attachments/assets/1b1aca7c-4dc4-420f-a212-5f564c80ff23)

**Comment by tedhinklater** [comment]
Hey thanks for taking the time to lemme know, it's appreciated. The theme's been [updated](https://github.com/tedhinklater/finimalism/commit/ed0679a10763acfb331c15b871108b2a9ef38dec) and the @import link should update too soon. Thanks again!

**Comment by Dress4Excess** [comment]
It looks gorgeous now!
Thanks!!
