### ISSUE TITLE
Bug Report: Loss of Access to Interactive Preview Menus

### ISSUE THREAD

**Issue by Mercedezs** [tedhinklater/finimalism#9]
The latest commit  f66f249 has introduced a bug that prevents access to the interactive menus in the preview section. Specifically, the options to mark items as played and access other settings are no longer available. I am currently using version 10.9.11 of the web player.

Current theme view.
![tema](https://github.com/user-attachments/assets/0e5822c0-8899-4eb9-bc7f-5b9523310d5b)

Default theme view, which displays the menus correctly.
![tema](https://github.com/user-attachments/assets/5cb756fe-4f00-4905-a8b8-b84e740544ce)

Thank you for your attention to this issue.

Best regards

**Comment by tedhinklater** [comment]
ohh my bad, I've undone it

**Comment by tedhinklater** [comment]
ty Mercedezs

**Comment by Mercedezs** [comment]
It seems that it's still the same

**Comment by tedhinklater** [comment]
It might take a while to update, this is the fix though 

.cardOverlayButton-br {
  display: flex !important;
}

**Comment by Mercedezs** [comment]
You’re right, my friend. I made a copy in my fork and recreated the jsDelivr, and it worked 100%. I tried to purge the cache on jsDelivr, but it didn’t work. I created a new jsDelivr link from your last commit just to test, and it worked. Now we just have to wait for the CDN to update, and the fix will be applied. Thank you very much for your attention
